# Generated by Django 5.0.7 on 2024-08-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Deposite'), (2, 'Withdrawal')], null=True),
        ),
    ]
